name: Deploy

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  deploy:
    name: Deploy the branch

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://amitsingh-007.github.io/stacks-game/
          environment: production
      
      - name: Clean install dependencies
        run: npm ci

      - name: Deploy my app
        run: npm run build
